### ISSUE TITLE
undefined method `each_with_index' for #<Split::Persistence::SessionAdapter:0x007fb47455fd18>

### ISSUE THREAD

**Issue by zitooon** [splitrb/split-analytics#11] opened 2015-01-15 08:41 UTC
Just updated a project of mine and got this error.

This happens in analytics.rb : 

``` ruby
    def custom_variables
      return nil if ab_user.nil?
      arr = []
      ab_user.each_with_index do |h, i|
        arr << "_gaq.push(['_setCustomVar', #{i + 1}, '#{h[0]}', '#{h[1]}', 1]);"
      end
      arr.reverse[0..4].reverse.join("\n")
    end
```

Gemfile.lock :

```
    split (1.1.0)
      redis (>= 2.1)
      redis-namespace (>= 1.1.0)
      simple-random
      sinatra (>= 1.2.6)
    split-analytics (1.0.0)
      split (>= 1.0.0)
```

Do you have any clue ? Thanks a lot.

**Comment by andrew** [comment] 2015-02-06 17:18
@zitooon sorry for the delay, looks like i broke something in the latest version, I suggest switching back to 0.4.0 for now.

**Comment by Bodacious** [comment] 2015-04-13 13:50
This one got me today too ><

Can you leave a comment here when the issue is fixed please :)

**Comment by andrew** [comment] 2015-04-14 20:59
I've pushed a fix for it, would be good if you can give it a try on master to see if it's solved your problem

**Comment by hagail** [comment] 2016-01-13 15:31
Hi @andrew,
Any news on that? I'm getting it both in the latest version and in 0.4.0
Thanks.

**Comment by andrew** [comment] 2016-01-13 15:33
@hagail have you tried using the code on master?

    gem 'split-analytics', :require => 'split/analytics', github: 'splitrb/split-analytics'

**Comment by hagail** [comment] 2016-01-13 15:48
yay, it works. Thanks @andrew :)

**Comment by andrew** [comment] 2016-01-13 17:05
Just released the latest copy from github as 1.0.1 to rubygems: https://rubygems.org/gems/split-analytics/versions/1.0.1

**Comment by joemasilotti** [comment] 2019-03-29 12:52
This issue looks to have popped up again. I tried both 1.0.1 and directly from GitHub and am reporting the same exception.

```
NoMethodError - undefined method `each_with_index' for #<ActionDispatch::Request::Session:0x00007fcd16405160>:
  app/views/layouts/application.html.erb:20:in `_app_views_layouts_application_html_erb__342287938765870022_70259377258700'
```

**Comment by andrehjr** [comment] 2019-04-03 17:34
Hi @joemasilotti, can you test again directly with master? It should be ok now.

I'll release a new version soon.

**Comment by joemasilotti** [comment] 2019-04-03 20:04
Works for me! Thank you, @andrehjr.

**Comment by svoop** [comment] 2022-02-22 01:20
@andrehjr @andrew Wow, this one just bit me in the bullocks while rolling an otherwise smooth, big deploy. (Murphy made sure the conflicting code is only present in production – just to spice things up a little.) The version from master works fine though.

How about cutting a release now, after all, it's almost three years now. Might save others from borderlining a heart attack like I have tonight. :wink: Thanks a bunch for considering it!

**Comment by andrehjr** [comment] 2022-02-22 01:49
@svoop Sorry you've been through that!

Yes, we need to make a new release. I'll push a new version.

**Comment by andrehjr** [comment] 2022-02-22 23:10
Pushed v1.1.0.

**Closed by andrehjr** 2022-02-22 23:10 UTC
